### PR TITLE
Bug/list tag text overflow

### PR DESCRIPTION
**Pull request by Bobby-Tav**
## Description

I fixed the spacing issue that was happening with the tags on the list display. 

Fixes # (Tags in list mode are not fully responsive to screen size or tag length.)

Video coming soon...
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by MMostella — APPROVED** [review]
Good catch and execution!

**Review by allisonhomem — COMMENTED** [review]
It looks like your edits fix the tag alignment! Would love to see a video to see how it looks. Also, there are some linting warnings about unused variables, but those might be cleaned up in the "refactor" pull request.

**Review by Grantzho — COMMENTED** [review]
looks good

**Comment by stu-wd** [comment]
really excellent logging all your commits so that all of us could track the progress along the way.

**Pull request closed without merging**
