### PR TITLE
Feature/card view icons

### PR DESCRIPTION
**Pull request by SomeiLam**
## Description

Jennifer and me (Amy) were working on adding list/thumbnail view icons.
[[video](https://www.loom.com/share/604c90c55f0f4e7cac169e03c207376c)]
Hover effect: [[video](https://www.loom.com/share/2acca92d316a410094000ba2cabc64f0)]

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by MMostella — APPROVED** [review]
Great work Amy and Jennifer! Yall are on it!

**Review by Klove-A — APPROVED** [review]
Looks good, thanks for getting this pushed up so promptly.

**Review by allisonhomem — APPROVED** [review]
This looks great! Good work!

**Review by Bobby-Tav — COMMENTED** [review]
Those Icons look great, My only suggestion is that we put like a popover each one so the user would be able to know what each of those icons mean.

**Comment by SomeiLam** [comment]
> Those Icons look great. My only suggestion is that we put like a popover on each one of the icons, so the user would be able to know what each of those icons mean.

That is a good idea, let talk about it tomorrow standup

**Review by xsong0306 — COMMENTED** [review]
Love the hover effect, Amy! Excellent job 😄

**Review by Bobby-Tav — APPROVED** [review]
Awesome Blossom it looks great

**Review by jinjahninjah — APPROVED** [review]
Looks great, the linter is throwing a warning for unused variables, but great otherwise.

**Pull request merged**
