### PR TITLE
Feature/bordered cards

### PR DESCRIPTION
**Pull request by allisonhomem**
## Description

<a href="https://www.loom.com/share/00f96e71f5b84d51aace586d8950e173">
    <p>Screen Shot - 14 December 2021 - Watch Video</p>
    
  </a>

Mason Mostella and I worked together to add CSS styling to the cards and to the background so as to make each card distinguishable. The issue motivating this change was that the plain background and lack of vertical separation of cards could have made it unclear to a user which file the user was bookmarking by clicking on the bookmark icon. We believe adding a distinct background color, bottom margin and border to the card, along with a 'lift upon hover' functionality solved this issue. For more details, please see the video above.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jMisch44 — APPROVED** [review]
Looks good!

**Review by steinmikey — APPROVED** [review]
A little code can go a long way. These changes look great! It's definitely clear which tag belongs to what document now.

**Comment by stu-wd** [comment]
I second what Michael said - a little code can go a long way. These changes reinforce so much to the user!

- We are mixing `px` and `%` in our styling. Especially on the new `position: absolute` addition to our bookmark, we will want to make sure that it is not going wonky as we change screen sizes. Going through the entire code base and creating uniformity between our styling (`padding` and `margin` mostly) can be something we knock out next week on the UX team.
- I really like that you took into account the logo's color palette. Your explanation during Design Critiques today with Coolors (from complementary colors to the "how does this look to someone affected by colorblindness") tell me that you are thinking about accessibility outside of your own user experience. Excellent work!

**Comment by stu-wd** [comment]
OH! @MMostella @allisonhomem - last thought:
- Will we be able to use this same styling when we switch to `list` view?

**Review by dominthebox — APPROVED** [review]
I agree with everything that's been said so far, the emphasis on the cards looks so much better, its amazing how some code can make such a huge change. I'm also curious like @stu-wd about the `list` mode, will it have similar styling? Overall great work so far team, its looking so much more polished compared to when we started on it two weeks ago!

**Comment by MMostella** [comment]
> OH! @MMostella @allisonhomem - last thought:
> 
> * Will we be able to use this same styling when we switch to `list` view?

I will get with Allison tomorrow (12-15) and see about checking the list layout and deciding if the bookmark needs to be moved. The latest of the main today had a bug with the different display views, so was not able to be checked or changed when this was done.

**Review by Bobby-Tav — APPROVED** [review]
That new Display look amazing! i would love to see those changes implemented on the List view as well. Awesome job!

**Pull request merged**
