### PR TITLE
Feature/remove the words from the logo

### PR DESCRIPTION
**Pull request by stu-wd**
## Description
Per Brian's request, the words from the logo have been removed. I edited the original logo file, created and saved another called "HRF_Logo2". I left the original in tact should we need to revisit.

[Video](https://www.loom.com/share/2179bb6f954342f0b085922837e06844)

Fixes # (issue)
Cosmetic issue.

## Type of change

Please delete options that are not relevant.

- [?] Bug fix (non-breaking change which fixes an issue)
- [X] Stakeholder request.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by sarahdherren — COMMENTED** [review]
The description on the pull request is consistent with the updates made.

**Comment by jMisch44** [comment]
Why did your package-lock.json have so many changes?

**Comment by stu-wd** [comment]
> Why did your package-lock.json have so many changes?

I'm not quite sure. Ryan shared one yesterday that had like 13k lines missing, so I wonder if this is similar.

**Review by jMisch44 — APPROVED** [review]
Looks good

**Review by Klove-A — APPROVED** [review]
Commits are clear and relevant and the description describes what you're doing.

**Review by MMostella — APPROVED** [review]
The pull request is well described and well implemented!

**Pull request merged**
