### PR TITLE
Feature/bookmark actions

### PR DESCRIPTION
**Pull request by collerhatguy**
## Description

Added action that calls backend api to get bookmark ID's and then calls the DS api to get those documents.
To be used by later developers.
https://www.loom.com/share/5c2f6bc8bb0b469bb0fef163cb6c65e2 

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Klove-A — APPROVED** [review]
Looks good to me. description covers changes made, each commit is informative but not overly wordy and you provided a video walk-through of what changes you made to the code and why.

**Review by dominthebox — APPROVED** [review]
Code looks clean, dry, and implements functions that bring us closer to achieving the bookmark task, great work.

**Review by jMisch44 — APPROVED** [review]
Looks good! The video explains your reasoning well

**Review by SomeiLam — APPROVED** [review]
Looks good

**Pull request merged**
