### PR TITLE
Feature/search functionality

### PR DESCRIPTION
**Pull request by caralocke**
## Description

Created search functionality using axios call with the endpoint provided by DS and handled state using Redux. This allows users to search the document database using keywords/terms and populates the results. You can then click on a document from the list of search results which redirects user to the box account to view the desired document. Used thumbnail endpoint provided by DS to provide thumbnail view of documents in search results view.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

## Loom Video:

https://www.loom.com/share/b97e8a34d41c4327b7536ba796542729

### CODE REVIEW

**Review by fervelgo — APPROVED** [review]
Loving the added test docs. Also the cleanup in exports and imports, well spotted.

**Review by BradfordMez — APPROVED** [review]
Awesome work Y'all! Search functionality is looking great!

**Review by collerhatguy — APPROVED** [review]
Cara, Rimsha, and Bailey were a big part in fine-tuning the final aspects of this feature. I can't wait to work with them more in the future.

**Review by JLeegwater — APPROVED** [review]
Great job on this! Was the .env.sample meant to be changed?

**Review by juliane1999 — APPROVED** [review]

**Review by HeyAnwar — APPROVED** [review]
Looks amazing ! Great job implementing this feature.

**Review by bevanger — APPROVED** [review]
It was great to work with Cara, Jacob, Rimsha, and Ryan on this project. Great job problem solving and getting this to work. Thanks for working so hard.

**Comment by Andrewschaer** [comment]
This looks great!  Awesome job and clean code.  Really like the link to the box PDF when you click the card.

**Review by rkshockey — APPROVED** [review]
It looks like you guys did some good cleanup in here as well, I'm glad to see it. Good job getting this important functionality off the ground!

**Review by engegreg — APPROVED** [review]
Looks like everything was accounted for, very good PR.

**Review by bverfurth — APPROVED** [review]
Everyone did a great job implementing the functionality!! Nicely done!!

**Review by nora-exe — APPROVED** [review]
Cara & FE friends: Very articulate, easy-to-understand PR description. Description & changes also demonstrate solid collaboration with DS - love to see it. Very thorough Loom demo, bonus points for making yourself available for questions at the end. Great work!

**Comment by tdubs42** [comment]
[FE can send a search query to the DS search endpoint and get a response](https://trello.com/c/ih15onJm/113-fe-can-send-a-search-query-to-the-ds-search-endpoint-and-get-a-response)

**Pull request merged**
