### PR TITLE
changed img tags to SVG components

### PR DESCRIPTION
**Pull request by tdubs42**
UX will need to restyle the size of the SVGs

## Description

Per the product review discussion I changed the  elements to imported SVG components

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by Andrewschaer** [comment]
Nice update, Tdubs!  Sometimes the smallest things can make a big difference.  The bookmarks will definitely be easier to work with and style with this update to SVG components.

**Review by Andrewschaer — APPROVED** [review]
Nice update, Tdubs! Sometimes the smallest things can make a big difference. The bookmarks will definitely be easier to work with and style with this update to SVG components.

**Review by jMisch44 — APPROVED** [review]
Looks good!

**Review by jMisch44 — APPROVED** [review]
Looks good!

**Comment by SomeiLam** [comment]
Very clean! Nice.

**Review by SomeiLam — APPROVED** [review]
Looks nice!

**Pull request merged**
