### PR TITLE
feature/sticky-nav

### PR DESCRIPTION
**Pull request by stu-wd**
## Description
We added `position: fixed` to the header so that the user always has access to the header.

Also, adjusted `margin-top` on the LandingContainer.js so that the cards are entirely visible.

[Video](https://www.loom.com/share/2d498034a48c4104aa151409037bad83)

## Type of change

Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by sarahdherren — COMMENTED** [review]
Video description clear and explains the need for feature. Pull request description concise.

**Comment by stu-wd** [comment]
currently still working to make this "responsive", ie -- disappear on scroll down, but reappear once the user scrolls up.

**Review by sarahdherren — APPROVED** [review]
Video description clear and explains the need for feature. Pull request description concise.

**Review by xsong0306 — APPROVED** [review]
Awesome work Stu!! Clear and concise description.

Would also appreciate a quick API demo of the feature :)

**Review by SomeiLam — APPROVED** [review]
Looks nice

**Review by Klove-A — APPROVED** [review]
Looks good, clear description and informative commits.

**Review by dominthebox — APPROVED** [review]
Code looks clean, I really like that you added a little margin to make everything look more uniform. Only comment/question I have is about the warnings under Files changed, are useEffect and useState being imported into the Header file but not being used? Maybe this was addressed already or simply awaiting to use them for another feature/pull request. Overall looks great.

**Comment by stu-wd** [comment]
> Code looks clean, I really like that you added a little margin to make everything look more uniform. Only comment/question I have is about the warnings under Files changed, are useEffect and useState being imported into the Header file but not being used? Maybe this was addressed already or simply awaiting to use them for another feature/pull request. Overall looks great.

@dominthebox in this particular PR, they are unused. Currently working through another PR for more CSS functionality and using them in that update. Should be released tomorrow!

**Comment by dominthebox** [comment]
Figured you were on top of it @stu-wd haha great work looking forward to the next PR! Keep it up!

**Pull request merged**
