### PR TITLE
Feature/list design

### PR DESCRIPTION
**Pull request by Bobby-Tav**
## Description

Thomas, Jonah , and myself finished the design of the card in the list display to reflect how the wireframe looks like. We made the tags hold more characters so that the user is able to see  more of the tag and not just six characters like in the thumbnail view.

[Video](https://www.loom.com/share/bd1e7aa7a64e4e189d05885caac2d683) 
## Type of change

- [x] Styling of a feature

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by sarahdherren — APPROVED** [review]
Your changes are described in the pull request and video and files changed were necessary to implement the feature. Nice job on committing along the way.  The video preview of the site shows that your implementation matches the current wireframe/mock-up of list view.

**Review by christina-yun — APPROVED** [review]
Overall this looks really clean. Thank you for putting in the comments that outline what is happening in the card -- it was a lot easier to see what the intention was after the the comments

**Review by Klove-A — APPROVED** [review]
Looks like a good pull request to me. Good description, I like seeing the implementation of the code in the video. Clean code keeping best practices and pre-existing file structure in mind when it comes to naming.

**Comment by stu-wd** [comment]
It's great to see the commits along the way. It helps to give context to how you were solving problems.

Thoughts:
- Is there anyway that we can reinforce to the user that they are on list/thumbnail? Perhaps we could add a thicker border to the type of display that the user has selected.
- There's some mixture of `rem`, %`, and `px`. We will need to do a sweep of our app sometime next week to create uniformity in our padding and margins.

Overall, I think that this is a big contribution. I especially like that the user is presented with more information immediately versus having to click/hover to gather more info (thinking tags and the path being visible).

**Review by dominthebox — APPROVED** [review]
I'm really enjoying the new List Mode View, I like how the tags are spaced and more readable to the researchers. You did a great job walking through the code and demoing the results in the video walkthrough. The code looks clean which makes this a great addition to the main branch, nice job team.

**Pull request merged**
