### PR TITLE
Feature/font stylings

### PR DESCRIPTION
**Pull request by allisonhomem**
## Description

Added a default font of "Open Sans Condensed" with a back-up font of 'sans-serif' for aesthetics and readability.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by MMostella — APPROVED** [review]
Great job changing font!

**Review by jMisch44 — APPROVED** [review]
Looks good!

**Review by Klove-A — APPROVED** [review]
Looks good, can't wait to see the new font!

**Comment by stu-wd** [comment]
neat, excited to see how this looks. I honestly hadn't done much with fonts since react so it's nice to see how this would be implemented for personal work.

**Pull request merged**
