### PR TITLE
Feature/responsive search results

### PR DESCRIPTION
**Pull request by sarahdherren**
## Description
As a user the landing card result page will be responsive to my screen size.
I implemented an object in the gutter property of row for responsive grid spacing for the articles that are returned as cards. I also over-rode the default setting of start for justification to match the current Figma wireframes showing the results displayed centered.

[video](https://www.loom.com/share/127928c5345c473c91c404cf81a9f000)

Fixes # (issue)
Prior to responsive implementation the card results were stacking upon each other on smaller screen widths.

## Type of change

Please delete options that are not relevant.

- [ X ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] I have removed unnecessary comments/console logs from my code
- [ X ] My changes generate no new warnings
- [ X ] I have checked my code and corrected any misspellings
- [ X ] No duplicate code left within changed files
- [ X ] Size of pull request kept to a minimum
- [ X ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by stu-wd** [comment]
[Docs re: AntD's grid and gutter](https://ant.design/components/grid/)

@sarahdherren this looks good and follows best procedures. Your video helped to give more context. I've linked the docs in case anyone needs to see them in greater depth.

**Review by xsong0306 — COMMENTED** [review]
Hi Sarah, I was not able to access your Loom link (maybe it's something on my end, but I was able to watch the Loom videos from other PR's).

**Comment by sarahdherren** [comment]
> 

I neglected to put the url into the url parenthesis - great catch! thank you, it works now

**Review by Klove-A — APPROVED** [review]
Looks good to me. The code accomplishes the goal, description starts with a user story and goes on to describe changes made and the videos walks through what coding you did

**Review by xsong0306 — APPROVED** [review]
Great job!!!

**Review by MMostella — APPROVED** [review]
PR is very well constructed and descriptive! Great job

**Pull request merged**
