### PR TITLE
Feature/add favicon

### PR DESCRIPTION
**Pull request by tdubs42**
## Description

Folks from the web side added a favicon via favicon.io, added the necessary files and HTML elements to the project and index.html respectively.

## Loom Video
https://www.loom.com/share/192678ace88142daa6ffd5fd2a15baf7

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by bevanger — APPROVED** [review]
Great job adding the favicon, thank you for showing us how to do it

**Review by bverfurth — APPROVED** [review]
You did an awesome job showing everyone how to use the favicon.io. Great work!!

**Review by caralocke — APPROVED** [review]
Was a great lesson for anyone who didn't know how to do favicons before. Happy to see it!

**Review by rkshockey — APPROVED** [review]
Everything is clean and concise, good to have this added.

**Review by juliane1999 — APPROVED** [review]
Learned something new today, thanks!

**Review by BradfordMez — APPROVED** [review]
Looks awesome! Great job showing off how the favicon works!

**Review by RimshaSaleem — APPROVED** [review]
Great Job!

**Comment by tdubs42** [comment]
[Add HRF Logo as a favicon and change the title of the app.](https://trello.com/c/1Ql4FbkU/11-add-hrf-logo-as-a-favicon-and-change-the-title-of-the-app)

**Review by nora-exe — COMMENTED** [review]
This was a great group activity for learning a new feature/function, and I'd really like to see more of this in the future!

**Review by Andrewschaer — COMMENTED** [review]
Awesome touch to make the application look and feel professional by including the favicon!

**Pull request merged**
