### PR TITLE
Feature/card list styling

### PR DESCRIPTION
**Pull request by Andrewschaer**
## Description

This update focuses on fixing the image cover size of landing card to better fit within the border of a card, adding a css reset for the application, & replacing the existing loading component with a loading spinner animation from Ant Design.

Co-Authors:
Jacob Shomali

<a href="https://www.loom.com/share/453366529f754a178cf722e67993017b">
    <p>Loom | Free Screen & Video Recording Software - Watch Video</p>
    
  </a>

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by collerhatguy — APPROVED** [review]

**Review by HeyAnwar — APPROVED** [review]

**Review by jhebert1994 — APPROVED** [review]
Looks good

**Review by RimshaSaleem — APPROVED** [review]

**Review by rkshockey — APPROVED** [review]
Everything looks solid. I especially like that you brought in the spinner.

**Review by fervelgo — APPROVED** [review]
Looks a lot better. Great weeerk!!

**Review by MMostella — APPROVED** [review]
Well described and well done!

**Review by sarahdherren — COMMENTED** [review]
Your video is excellent walking us through the changes and how they were implemented.

**Comment by stu-wd** [comment]
I especially like that the CSS reset was imported in the index.js.

**Review by jMisch44 — APPROVED** [review]
Looks good! I like the spinner being added

**Pull request merged**
