### PR TITLE
adds onClick to 'tags' to search tag

### PR DESCRIPTION
**Pull request by stu-wd**
## Description

As a user, I can click a tag on the card and create a new search for that particular tag.

Connected the 'searchDocs' action to the tags per card.

[Video](https://www.loom.com/share/3d23a8b5276a41d89cc4237286c1f90a)

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by MMostella — APPROVED** [review]
Great functionality!

**Review by xsong0306 — APPROVED** [review]
Awesome work!!

**Review by jMisch44 — APPROVED** [review]
Looks good

**Review by Klove-A — APPROVED** [review]
Looks great! Description matches changes made and are not overly wordy.

**Pull request merged**
