### PR TITLE
Bug/reducers

### PR DESCRIPTION
**Pull request by jMisch44**
## Description

Michael, Klove, and I (Jennifer) worked on fixing some of the bugs that were caused by the merging of the refactor. This fixes the bookmark page showing box ids on the bookmark page, fixing the home button in the header to be functional and more things involving refactoring the redux merge.

[Video](https://www.loom.com/share/7e2d95406f734f63b625359bd42322f1)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by allisonhomem — APPROVED** [review]
This looks good! Thanks for doing this!

**Review by SomeiLam — APPROVED** [review]
Thanks for fixing. It looks good.

**Review by Bobby-Tav — APPROVED** [review]
Awesome Blossom! This is gonna be a big help! Thanks.

**Comment by stu-wd** [comment]
this looks great. I appreciate the step-by-step video of what changes you made.

**Pull request merged**
