### PR TITLE
fixed bug causing app to crash if no search term entered

### PR DESCRIPTION
**Pull request by collerhatguy**
## Description

- entering a empty search cause the app to crash due to an invalid api request. We entered a guard clause that prevented this from happening and gave an alert to the user letting them know that they need to type a non empty request
https://www.loom.com/share/ab2dd97784964bc88682f4c57929a8cc 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by collerhatguy — COMMENTED** [review]
It's ready spaghetti, my favorite food

**Review by nora-exe — APPROVED** [review]
Timely efficient bug fix + error message for user! The more we communicate with the user the better 👍 LGTM, GJ Jacob & Bailey!

**Review by HeyAnwar — APPROVED** [review]
nice work

**Review by jhebert1994 — APPROVED** [review]
Great catch and fix.

**Review by RimshaSaleem — APPROVED** [review]

**Comment by Andrewschaer** [comment]
Nice catch and quick easy fix to make sure we're covering all expected user paths.

**Review by rkshockey — APPROVED** [review]
Good catch, this was an important thing to get fixed. Well done, guys.

**Review by fervelgo — APPROVED** [review]
Looks solid!

**Review by MMostella — APPROVED** [review]
This bug was caught and successfully fixed

**Review by jMisch44 — APPROVED** [review]
Looks good!

**Pull request merged**
