### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by stu-wd**
## Description
First, I want to lead off with a cover from another favorite band of mine from a show I went to in November - [**Goose** - _Please Forgive Me_  - (David Gray original)](https://www.youtube.com/watch?v=HYDzS-qiLxk)

I do that because I realize that I have done A LOT of work on this branch. Once I started, I realized that there were a ton of things that could be done to enhance the flow of our files and the feel of our app. So, I am sorry that this is a large push, but as far as I can tell, the functionality of my branch remains the same as our current version of `main`.

All that being said (did you know I can talk a lot?), I'm going to try and organize this summary and my video in the best way that I can.

[Video 1](https://www.loom.com/share/a197ded66e8647e28c341c492895677b
)
[Video 2](https://www.loom.com/share/14f8d31d7b8e43d580f6f2902cf66ae4
)

Deletions:
- the `Search` folder that was in `src/components/pages/Search`. We were initially using this when rendering `website.com/search`, but becuase we are not using that particular route, I deleted the entire file and adjusted imports accordingly.
- the `Styles` folder from our root. Again, I noticed that the only file in there was `theme-override` and we were not using it. Upon rebooting the next morning, my app would not launch because the imports were in our `craco.config.js` file. They have since been deleted and the app launches without issue.
- `src/state/index.js` has been deleted as it was an empty folder.
- `src/state/contexts` has been deleted as its content was empty.
- removed some unneccessary CSS files and used inline stlying to create uniformity.
- removed `isRequired` from the `isFavorite` prop so the app would launch without console error.

File Organization Refactor:
- `src/state/reducers` has now been split  up into: `/bookmarks`, `/docs`, and `/searches`. These are being brought together in `src/state/reducers/index`.
- `src/state/actions` has now been split  up into: `/bookmarks`, `/docs`, and `/searches`.
- makes `Header` folder in `src/components/common`, moved all related files to the folder, and adjusted imports.
- makes `ColTag` folder in `src/components/common`, moved all related files to the folder, and adjusted imports.
- makes `Tags` folder in `src/components/common`, moved all related files to the folder, and adjusted imports.
- makes `Stock` folder in `src/components/common` and moved (what I consider to be) unused files in there. These include: `Button`, `FormButton`, `FormInput`, and `List`.

Code Refactor:
- the `img` tags on `LandingCard` have been revised to decrease code and increase DRYness. I used a ternary inside of the `img` attributes that is state-dependent.
- removed `getDocs` from our `src/compoents/common/ReduxList`. It was being called on launch and preventing our `GoogleClone` from being launched.
- adjusted the `height` of our background color on `GoogleClone` so that the entirety of the screen is the light tan.
- removed bookmarks button from the `GoogleClone`. If that page is showing, it is because the user does not have bookmarks, so there is no reason for the button to be visible.
- removed `hoverable: true` from our landing cards.
- removed `span={6}` from the `docs.map` on `src/components/pages/Landing/LandingCardList`. This makes the thumbnail view responsive. The span was adding space to the outside of the cards. Now, the number of cards displayed is dependent on the screen size. Previously, the cards were being squished together as the screen changed.
- @allisonhomem and @MMostella pushed up something that I copied. I expanded the background color to cover the page and moved the `LoadingComponent` to the middle of the screen.
- refactored the logic in `LandingCardList` (now `LandingCardResults`) so that we didn't have 2 separate components. The only thing that was changing was the styling, so I created some ternaries that now changed dependent on the truthiness of `state.docs.cardView`.
- created stateful reactions to our `List` and `Thumbnail` buttons in `Header` so that they disappear depending which view is shown.

Issues still remaining:
- Clicking on the Bookmarks button does not render a change. @Klove-A and I believe that the issue stems in `src/state/reducers/docs` in the `getDocs` function. I placed logs through the entirety of the function. The only one that ever registered was in the `catch`, meaning that our `try` block is never running. Once we are able to hash that out, I suggest separating `getDocs` and creating a `getBookmarks` action. That way, we would be able to further separate our functions into their appropriate folder within `src/state/actions`.
- The list view for our documents needs some love. I currently have it set to `width: 60vw` to mimic what we had before, but it still needs to be adjusted. Especially the font size of the title.
- Additionally, @sarahdherren and I are planning to hash out the design of the thumbnail views. One idea: moving the title to the top to draw the user's attention to the top (if we place bookmark icon there, it reinforces to the user what it's for). Sarah has been hashing out the modal for our custom tags feature.

Summary:
This was a lot and I am terribly sorry for making such a large push. Once I got in the groove, I had trouble stopping. Overall, I do feel like the code has been refactored to represent DRY principles and to be a bit easier to understand. I'll be around all weekend should any questions or merging issues arise. If you've made it this far, then please enjoy another tune... after all, it is winter and winter means soup season. And in this context, gumbo is soup - [**Phish** - _Gumbo_](https://www.youtube.com/watch?v=iiz6Qdx9Vgg)

## Fixes (issue)
- Deleted code that was not being used.
- Deleted components that were not necessary and instead tied the views to state.

.....bonus song because during the midst of all these changes I became a reallllly big fan of `git stash` so I could switch between branches. [**Phish** - _Stash_](https://www.youtube.com/watch?v=Mmqna7xOfJs)
`{stuartIsRidiculous ? 'maybe so' : 'maybe not'}`

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by sarahdherren — APPROVED** [review]
The changes are so well documented. The refactoring of the card styling and applying it to one component only eliminates the redundancy we discussed and make it so much easier to implement future features moving forward. The architecture is now more clear and easier to navigate through. Your commits are well described and applied often.

**Review by Bobby-Tav — APPROVED** [review]
I agree with @sarahdherren it would save more time adding new features to the card components. and it makes the code cleaner and easier to traverse.

**Review by allisonhomem — APPROVED** [review]
This looks great! Much better organization and the detailed explanations were super helpful!

**Review by LSislowski — APPROVED** [review]
Good thorough documentation on the changes you made. Looks great!

**Pull request merged**
