### PR TITLE
moved the onClick from the whole card div to the image

### PR DESCRIPTION
**Pull request by fervelgo**
## Co-authors
Andrew Schaer
Rimsha Saleem

## Description

We moved the onClick in the LandingCard component to the image element in the cover. 
It used to be part of the div that contained the whole Card element, such that clicking on **anything** in the card would trigger the onClick. We don't want other elements in the card, like the bookmark button for example, to trigger a link to the specific document.
Now it only links to the document when clicking the preview image displayed on the Card element.

Fixes # (issue)
https://trello.com/c/ORP9yDGf/114-when-you-click-a-document-card-the-entire-card-is-a-link

## Type of change
Bug Fix

##Video

https://www.loom.com/share/c79b2d70d48041b09485208298df7f57

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by nora-exe — APPROVED** [review]
Fernando & friends - thank you for addressing this bug so fast. Good work 👍

**Review by rkshockey — APPROVED** [review]
Clean, simple bug fix; good to go.

**Review by fervelgo — COMMENTED** [review]
Changed back the .env samples to example values.

Everything else, tested and working!

**Review by jhebert1994 — APPROVED** [review]
Looks good, nice job fixing that so quickly.

**Review by BradfordMez — APPROVED** [review]
Great job taking care of that bug!

**Comment by Andrewschaer** [comment]
Good teamwork on this one and thanks for leading in Liveshare, Fernando.  Clean, easy bug fix shifting that onclick code to the correct portion of the card.

**Review by bevanger — APPROVED** [review]
Great job fixing this bug, code looks great.

**Review by HeyAnwar — APPROVED** [review]
Nice job looks all fixed !!

**Review by JLeegwater — CHANGES_REQUESTED** [review]
The .env.sample should not have any real information in it. Once you delete that it looks great!

**Review by JLeegwater — APPROVED** [review]
Looks great! We will want to scrub the history of the real .env.sample data though

**Review by caralocke — APPROVED** [review]
Fantastic job, thank you so much for fixing this issue quickly!

**Comment by dagtag** [comment]
[When you click a document card, the entire card is a link](https://trello.com/c/ORP9yDGf/114-when-you-click-a-document-card-the-entire-card-is-a-link)

**Pull request merged**
