### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by stu-wd**
## Description
Removes some unnecessary console.logs.
Adds `key` to the tag to avoid the console error.

[Video](https://www.loom.com/share/5a2cba4b62fa436997f6a33491d506e1)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by sarahdherren — APPROVED** [review]
thanks for cleaning this all up Stu - looks great

**Review by Grantzho — APPROVED** [review]
Cleanup looks good.

**Review by Bobby-Tav — APPROVED** [review]
Stu, Thank you for pulling in the time to look over the code to get rid of those pesky console error. I appreciate it

**Review by MMostella — APPROVED** [review]
Thanks for the clean up Stu! Looks good

**Review by jMisch44 — APPROVED** [review]
Looks good! Thanks for going through and cleaning up the code. One question though, why did you add query to the reducer?

**Comment by stu-wd** [comment]
> Looks good! Thanks for going through and cleaning up the code. One question though, why did you add query to the reducer?

@jMisch44 good catch. I was working on some things and forgot to remove that. that part is unnecessary. thanks for catching that!

@paulstgermain we can probably wait until until all the PR's are done, then I can do another `cleanup` branch.

**Review by dominthebox — APPROVED** [review]
Cleanup looks great, we love clean code and getting rid of those sneaky console.log's! Keep it up!

**Review by SomeiLam — APPROVED** [review]
Looks nice! Thanks for cleaning it up.

**Review by techwulf — APPROVED** [review]
It looks really good

**Pull request merged**
