### PR TITLE
feature/shows the currentSearch term after user searches (by typing or clicking)

### PR DESCRIPTION
**Pull request by stu-wd**
## Description
Changed the "Search Directory" to be stateful so that the user is reinforced of their search query.

[Video](https://www.loom.com/share/006f47853b5d4c8c8dcbaf0c13250210)
## Type of change
- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jinjahninjah — COMMENTED** [review]
Looks great! This new feature is very helpful in reinforcing what search term they used and it's very visible. Nice Work!

**Review by Bobby-Tav — APPROVED** [review]
That is a niffy feature. But so useful. great video.

**Review by Klove-A — COMMENTED** [review]
I like this pull request, clear description of what changes you made and why they were needed. 
That being said, I haven't looked at headerStyle but do you think you'd be able to move the search results so they are centered on the page?

**Review by allisonhomem — COMMENTED** [review]
This looks great! I think this will be super useful for the researchers, especially since some of the tag names are so long.... speaking of that, I think you win an award for longest feature-branch name, lol

**Review by xsong0306 — APPROVED** [review]
Awesome work!

**Review by Klove-A — APPROVED** [review]

**Comment by stu-wd** [comment]
@Klove-A yeah the `headerStyles` is `text-align: center` so I think once we merge the branch that Allison worked on, it should look a lot better

**Comment by stu-wd** [comment]
@Klove-A nevermind it is not centered. I will find the right div and get it sorted

**Review by jinjahninjah — COMMENTED** [review]
Looks great and the feature is working perfectly, great job! There are a couple of warnings from GitHub's litner, page has a value but is not being used.

**Pull request merged**
