### PR TITLE
Feature/remove bookmark

### PR DESCRIPTION
**Pull request by jMisch44**
## Description

Amy and I (Jennifer) worked on the new feature of removing a bookmark from a users account. By clicking on the filled in bookmark icon, it will remove that bookmark from the users collection of saved bookmarks in the node.js database.

[video](https://www.loom.com/share/57b6066adc4247d4bc3787f523e5f9c7)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by stu-wd — APPROVED** [review]
@jMisch44 @SomeiLam again, really good work. especially working with an exisitng codebase and using redux. yall should be proud of yourselves.

this code follows best practice and strives to be DRY.

**Review by christina-yun — DISMISSED** [review]
Loved the video showing how all the code is interrelated and how it works to remove the bookmark.

Only thing is that I see from looking (and it won't let me comment) that there's some kind of linting error on your LandingCard.js doc for line 4.

**Comment by jMisch44** [comment]
@christina-yun 
That was in main from a PR that got merged before this PR, not sure what one of the UX engineers changed or why it was left in.

**Comment by sarahdherren** [comment]
> @christina-yun That was in main from a PR that got merged before this PR, not sure what one of the UX engineers changed or why it was left in.

we were just discussing via PM that we needed to remove that import. The attribute that the icon was being implemented with doesn't work with Ant Design, so the way it was used by the previous cohort was preventing the icon from loading. We are planning to address this in the UX Design critique to see if the expand arrow should/shouldn't exist as the whole card is clickable not just the icon.

**Comment by paulstgermain** [comment]
> Loved the video showing how all the code is interrelated and how it works to remove the bookmark.
> 
> Only thing is that I see from looking (and it won't let me comment) that there's some kind of linting error on your LandingCard.js doc for line 4.

I'm actually going to go ahead and dismiss this request for changes, as these linting errors stem from main and not from this particular PR. I think a better means of handling these would be in a separate PR - also gaining someone an extra PR for graduation!

**Review by dominthebox — APPROVED** [review]
Since @paulstgermain approved the check warning regarding the linter warning in LandingCard.js, everything else looks clean. Approving this for review before merge, nice work.

**Review by steinmikey — APPROVED** [review]
Commits are clear, the video review and code look good. Great Work!

**Pull request merged**
