### PR TITLE
Feature/navbar is responsive based on the user's scrolling action

### PR DESCRIPTION
**Pull request by stu-wd**
## Description
In the previous push regarding the `Header` (called `navbar` in branch name), it was a fixed position.
In this update, it's now responsive based on the user's scrolling.
On scroll down, the `Header` component disappears. Once the user scrolls up, it reappears.
Additionally, a helper function `debounce` was added to the `src/utils` folder.

[Video](https://www.loom.com/share/74ec471e6f7e40e7b8ec83a8ae65a855)

## Fixes  (issue)
No longer is the `Header` in a fixed position at all times

## Type of change

Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jMisch44 — APPROVED** [review]
Looks really good! Nice work!

**Review by christina-yun — APPROVED** [review]
Really enjoyed you walking through and showing how the sticky/vanishing nav bar works. The functionality of this is really going to make it comfortable for users to get the most out of this app!

**Review by MMostella — APPROVED** [review]
Looks good Stu! Keep rocking it

**Review by dominthebox — APPROVED** [review]
Code looks great @stu-wd really enjoyed the video demo of the navbar in action! Great work.

**Review by SomeiLam — APPROVED** [review]
The code looks nice, the video is clear. Also very helpful showing how it actually looks like on the application.

**Pull request merged**
