### PR TITLE
Feature/add bookmark

### PR DESCRIPTION
**Pull request by jMisch44**
## Description

Amy and I (Jennifer) worked on the feature of letting a user add a bookmark to the node backend database. We also changed the bookmark icon so that it would show on the individual document cards.

https://www.loom.com/share/5ad635616bcf4e7a985db75053fc3699

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by stu-wd** [comment]
@jMisch44 @SomeiLam 
- I see that yall changed the imports from `ReactComponent as BookMark`. Once this is all merged, we might need to revisit and make sure that it is still functioning. My concern is that there may have been updates to the code and that this might create a similar error that we ran into yesterday.
- in landingcard,js, I see that there is an `onClick` added to the `BookmarkOutlined` img tag. is there functionality to undo the bookmark feature?
- line 21 in landingcard.js, there is an `if` statement that doesn't have curly brackets after it, but then resets the `isFavorite` variable to true. I don't know if that works or not, but thought I'd add here that I didn't see the curly brackets. I am really curious to see what the answer is!

overall, the code and the flow works. it follows the practices and standards that are already in place.

I am excited to see how this works! really proud of you and the team for working through all those bugs to get this going!

**Comment by jMisch44** [comment]
- I'm not sure what's going on with the icon, we changed the imports because they weren't showing for us using the new way. So we went back to the old way when they were showing.
- The onClick that's going to be added to BookmarkFilled is removing a bookmark from the database, which is another feature we are going to implement in a different PR.
- The if statement without the curly brackets on line 21 in landingcard.js is just a syntax shorthand, which I used since it's only doing one thing and not multiple.

**Comment by stu-wd** [comment]
- The imports messed up for me yesterday when I pulled the most recent version of `main`, so there may have been other updates since then.
- Sweet! That's what I figured lol. I realized that you PR was called "add bookmark" so makes sure that the other feature isn't there lol.
- that's really cool. I didn't know javascript allowed that. thanks for the tip.

**Review by stu-wd — APPROVED** [review]

**Review by xsong0306 — APPROVED** [review]
Video description clear and explains the need for feature. Pull request description concise.

Awesome work guys!!! 😃  Would love to see a demo in API!

**Review by sarahdherren — APPROVED** [review]
The code is well explained in your video walk-thru. The pull request looks great. 

I am really excited about the bookmark function!

I was noticing the same thing Stu mentioned on the import, but sounds like it is working on your end.

**Review by dominthebox — APPROVED** [review]
Code looks clean and organized, great job implementing this feature

**Pull request merged**
