### PR TITLE
feature/pagination-update

### PR DESCRIPTION
**Pull request by Klove-A**
## Description

Michael and I (Klove) looked into styling options for the pagination element, we ended up adding an additional pagination element to the top of the page and centering both with some bottom padding and changing the results per page options to be multiples of four and five to fit nicely into the average user screen size. Also removed left padding from landing container because it was skewing everything off center.

[Video](https://www.loom.com/share/7ef168eaa95e4053b15602e9f8a8a158)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jMisch44 — APPROVED** [review]
Looks good!

**Review by MMostella — APPROVED** [review]
Great work with the pagination update!

**Review by SomeiLam — APPROVED** [review]
Looks very nice! Video is clear, showing the application and the changes of the code.

**Review by LSislowski — APPROVED** [review]
Great work and Loom video walkthrough.

**Comment by stu-wd** [comment]
really love that you gave the user the pagination option at both the top and bottom. for some reason, the weirdo in me likes the new options a lot more (perhaps because they are all even??). Idk, just feels cleaner than the previous options. good loom video walkthrough and explanation of the code.

**Pull request merged**
