### PR TITLE
Pagination Feature

### PR DESCRIPTION
**Pull request by steinmikey**
## Description

Klove Adams and I (Michael Steiner) implemented pagination for search results. We used the Pagination element from ant-design and redux to store relevant search parameters. A user can now select which page of results to view, and also change how many results are shown at once.

[LOOM Video](https://www.loom.com/share/6d156608d94549018912b742e1627f54)

• DS API - changed the get request to a post request to align with the DS database
• Header Component - updated onSearch to also call setCurrentSearch function and mapped state to props
• LandingCardList component - added the handleChange function for Pagination, this function searches the database whenever a page is changed or the number of items per page is changed
• Actions index - added a setCurrentSearch function to update any search parameters stored in state, updated the searchDocs function to include the page number and request per page in the query string
• Docs Reducer - updated initial state to include search variables, updated SET_DOCS case, added CURRENT_SEARCH case

Fixes # (issue)
Enables user to access all search results (instead of only 32)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by xsong0306 — APPROVED** [review]
Clear description and great new functionality!

Awesome work for getting this in guys :P

**Review by jMisch44 — APPROVED** [review]
Looks good, nice work getting the pagination functional.

**Review by sarahdherren — APPROVED** [review]
Your video walk-thru was excellent showcasing the feature and walking us through your implementation.

**Comment by stu-wd** [comment]
- Is there anyway we can expand the width of the select option? It fits the double digit numbers (10, 25, 50) well, but cuts off the last zero of 100.
- When we move to the next page, the page was loaded but the user's view started at the bottom. It would be better if the user is brought back to the top. This is something also happens if you are mid-way through the page, then enter a new search term. The user is "stuck" at its previous position despite the refresh of documents.
- Is there anyway that we can prohibit a user from seeing page numbers that might not exist? IE - let's say that searching "stuart" returns 114 results. If I have my pagination set to render 25 docs/page, then we would need 5 pages ((5 * 25) > 114) to show all the results. Our users could decide to click on pagination page 8 and possibly be met with no results.

Overall this is a HUGE feature though. This really added a lot of customability (if that's a word) for our user.

**Comment by Klove-A** [comment]
@stu-wd I would like to start off by thanking you for your comments, and provide the disclaimer that styling for pagination is not part of this pull request we were implementing functionality. Which is why we did not include styling in our description. That being said I will try to address your concerns.
- we are aware of that and I believe it can be fixed but I have not dived into the how yet, I am planning on addressing how to move forward with this in stand up tomorrow.
- this is not a pagination specific problem, if you search from the bottom or middle of the page you also stay where you are. So I think it is best to address it as a app wide issue.
- as it stands it should only show the number of pages relevant to search results returned / results-pre-page. If your page size is set to 25 and you have 30 results it will only show 2 pages if you have 25 or less results pagination won't show up at all.
- we thought about changing the name after the fact but the pool request rubric doesn't mention naming conventions so we decided to leave it.
I hope that was helpful in clarifying any questions and addressing any concerns you have, please ask if there's anything else you wanna know.

**Comment by stu-wd** [comment]
@Klove-A - sweeeet. we're aligned in our thinking (I'm going to steal a slackmoji from my old job and share it with you because it's just hilarious). I like that you decided to push up the MVP for this feature instead of doing everything that was possible.

**Pull request merged**
