### PR TITLE
Feature/tag modal

### PR DESCRIPTION
**Pull request by sarahdherren**
## Description

As a user I can add custom tags and delete tags from individual documents.

Ant Design's Modal (Animate component) is generating a new warning on render -  I found these discussions about it:
[https://issuehunt.io/r/ant-design/ant-design/issues/20262](https://issuehunt.io/r/ant-design/ant-design/issues/20262)
[https://github.com/ant-design/ant-design/issues/22493](https://github.com/ant-design/ant-design/issues/22493)

[video](https://www.loom.com/share/22f416bdae914924898f1394feb6340a)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by xsong0306 — APPROVED** [review]
Great job, Sarah!!

**Review by MMostella — APPROVED** [review]
Great work with the tags modal!!!

**Comment by jMisch44** [comment]
Question, will adding a new tag that's an empty string crash the page? Or just have an empty tag added to that card?

**Review by SomeiLam — COMMENTED** [review]
This is a lot of works. Great job and thank you!
Just tested that user can add an empty string for a tag but also can remove it easily. I think adding a checking makes it a better user experience.
Also, would it be better if we can place an add tag button next to the text input, since some user may not be able to use a keyboard, just copy and paste text will not be able to add a tag. I guess the 'Done' button and the cross in the top right do the same thing? If so, I don't think it is necessary to put both.

**Comment by stu-wd** [comment]
great question by @jMisch44 and good quick test by @SomeiLam.

@sarahdherren this is really great work and super impressive. you executed best practice with the axios calls and the code structure.  I appreciate all the commits along the way.

**Pull request merged**
